[package]
name = "axiom"
version = "0.1.0-dev"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
engine = { path = "../engine" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
